### ISSUE TITLE
v0.0.1 impl todo list 

### ISSUE THREAD

**Issue by M09Ic** [chainreactors/malice-network#6]
from demo to v0.0.1

## thread 1 @HuYlllc 
- [ ] client 
	- [x] 实现tui styles (已经重构)
		- [x] bar
			- [ ] 允许自定义文字内容 
		- [x] select
			- [x] 统一配色 
		- [x] confirm
		- [x] spinner
		- [x] table 
			- [x] 自适应宽度，并通过按键拉动属性展示 
	- [x] 实现armory
		- [x] 实现从 https://github.com/sliverarmory/armory/blob/master/armory.json 更新最新的数据源 
	- [x] ANSI相关的功能使用https://github.com/muesli/termenv 库重写
	- [x] 实现自适应颜色
	- [x] 导入配置文件 `./client ***.yaml` ,解析并验证配置文件, 并添加到configs目录中 
	- [ ] longhelp
		- [ ] 使用markdown渲染 
	- [x] 新增group与note命令, 用来分组管理session
	- [ ] tui
		- [x] 新增tui file explore
		- [x] 支持foot，显示keymap的帮助。 
		- [x] 在各个组件中统一keymap
		- [x] select 按回车后不清除掉其他选项, 只显示指定的选型
		- [x] file-picker代码同步到本地
		- [x] 提供table的搜索功能，能通过关键字快速跳转到指定行
		- [x] 新增组件console，可以适配原有的model，用来输入命令与原有的model交互
- [ ] 数据库
	- [x] 从数据库中恢复session 
	- [x] 从数据库中恢复tasks 
	- [x] 数据库中记录download与upload的记录
	- [x] 每次接收到任意implant的请求, 都更新session表的last相关字段
	- [x] session表添加多个字段
- [ ] 实现基本命令
	- [x] download, upload, sync 命令
		- [x] server端实现sync 
		- [x] client端实现download, upload
		- [x] server端 upload 最后一个block添加end标记
	- [x] website 命令 参考sliver实现 
	- [ ] client端系统基本命令
		- [x] id
		- [x] cat
		- [x] cd
		- [x] ls
		- [x] rm
		- [x] cp
		- [x] mv
		- [x] whoami
		- [x] chmod
		- [x] chown
		- [x] mkdir
		- [ ] ping (通过BOF实现)
		- [ ] curl (通过BOF实现)
		- [x] pwd
		- [x] ps
		- [ ] ifconfig 
		- [x] netstat
		- [x] env
		- [x] setenv
		- [x] unsetenv
-  杂项/bug修复
	- [ ] 实现client tasks展示, 以及相应进度条. 任务完成后从内存中删除, 只能在db中显示. 
	- [x] server 添加audit.log, 记录每一个操作
	- [x] 修复cert重复创建，重复添加到数据库的bug
	- [x] listener和client的证书实现不同的权限控制, 禁止使用listener的证书访问server的implant相关功能.反之亦然.
- server 
	- [x] server的--user 改为一组子命令， 支持添加/删除/列出所有的user
	- [x] server新增--listener命令, 功能类似--user, 支持listener相关的证书生成/删除
	- [x] 随机化证书生成的相关信息
	- [x] 实现tls证书生成相关的代码, 支持从配置文件中读，如果留空则使用随机值代替
	- [x] 重构证书生成功能相关代码
	- [x] 实现--deamon
	- [ ] 独立 listener
		- [ ] 通过命令直接注册对应的pipeline
		- [ ] 建立JobStream, 实现与server的交互
		- [ ] 使用client控制listener建立对应的pipeline
		- [ ] 使用client控制listener建立对应的website
## thread2 @M09Ic 
- client端
	- [ ] 实现profile, 允许定制自己的终端
	- [ ] 实现插件系统
		- [ ] 兼容sliver插件生态
		- [x] 实现alias
		- [ ] 实现extension
		- [ ] 实现module 
- server端
	- [x] 实现audit log
	- listener
		- [ ] 实现基本的listener cli
		- 实现pipeline相关的内容
			- [ ] grpc
			- [ ] client
			- [ ] udp/udps pipeline
			- [ ] http/https pipeline 
		- [x] 实现encryption wrap 
		- [x] 实现tls wrap 
		- [ ] 实现基本命令
	- [ ] 实现generate相关功能
- implant
	- [x] 重构implant core 
	-  实现基本命令
		- [x] cp
		- [x] mv
		- [x] cat
		- [x] rm
		- [x] mkdir
		- [x] ls
		- [x] cd
		- [x] pwd
		- [x] chmod
		- [x] chown
		- [x] env/setenv/unsetenv
		- [x] kill
		- [x] ps
		- [x] netstat
		- [x] upload
		- [x] download
		- [x] exec
		- [x] execute_assembly
		- [x] execute_shellcode
		- [ ] reg相关
		- [ ] ifconfig
		- [ ] spawn
		- [x] inline_assembly
		- [x] inline_shellcode
		- [x] execute-bof
- other
	- [ ] 编写文档
		- [x] wiki
		- [ ] roadmap
		- [x] 设计文档
## thread3 @nightRainy 
- implant
	- 实现基本框架
		- [x] 调度器
		- [x] 动态模块加载
		- [x] 清除winapi与windows-sys 依赖, 全部替换为windows (部分完成)
		- [ ] 接入 https://github.com/chainreactors/rem 作为流量部分能力
	- features
		- [x] bof
			- [ ] 集成常用BOF
				- [ ] https://github.com/REDMED-X/OperatorsKit
				- [ ] https://github.com/HavocFramework/Havoc 
		- [x] execute-assembly 
			- [x] 提供inline process版本  
		- [x] load-pe/load-dll module
			- [x] 提供inline process版本 
		- [ ] 动态patch feature、
			- [ ] custom process-inject 
			- [ ] custom dll loader
		- [x] shellcode-loader
			- [x] 实现shellcode loader 回显 
		- [x] spawn
		- [ ] memfd
		- [ ] sideload
		- [ ] token 模拟
		- [ ] 兼容sliver的extension
		- [x] 实现牺牲进程
		- [x] 实现父进程欺骗
		- [ ] 实现参数欺骗
		- [ ] 实现网络链接名欺骗
		- [x] 交叉编译Makefile
		- [x] [使用async-std和futures代替tokio](https://github.com/chainreactors/malice-network/issues/10)
			- [x] 删除老的channel
